language: node_js
node_js:
  - "12.16.1"
branches:
  only:
  - master
before_install:
  openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in super_secret.txt.enc -out super_secret.txt -d
deploy:
  provider: heroku
  api_key:
    secure: $encrypted_355e94ba1091_key
  app:
      master: my-app-staging
  on:
    branch: master
