language: node_js
node_js:
  - "12.16.1"
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: "59437a34-0f61-4356-a3f7-2ffcc2f31f05"
  app:
      master: my-app-staging
  on:
    branch: master
